"""
app.py

Provenance Guard — Flask API skeleton.

Implements the submission flow from planning.md:

    POST /submit
        -> Rate Limiter
        -> Detection Pipeline
              -> Groq            -> Score 1   (signals.groq_signal)        [M3]
              -> Stylometric     -> Score 2   (signals.stylometric_signal) [M4]
        -> Combined Confidence Score                                       [M4]
        -> Transparency Label                                             [M5]
        -> Audit Log (text, scores, label)
        -> Response (confidence score, label)

Milestone status:
    M3 (this file): Flask skeleton, rate-limited /submit wired to Signal 1,
                    structured audit log (JSONL, persisted) + GET /log.
    M4: second signal + confidence scoring (combine Score 1 and Score 2).
    M5: transparency label generation + POST /appeal.

Run:  python app.py   (serves on http://127.0.0.1:5000)
"""

import os
import json
import uuid
from datetime import datetime, timezone

from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address

from signals import groq_signal, stylometric_signal, combine_signals

app = Flask(__name__)


def _utc_timestamp() -> str:
    """Current UTC time as ISO 8601 with milliseconds and a 'Z' suffix."""
    return datetime.now(timezone.utc).isoformat(timespec="milliseconds").replace("+00:00", "Z")


def _attribution_from_score(score: float) -> str:
    """
    Map a 0.0–1.0 confidence score (0.0 = human, 1.0 = AI) to its attribution
    label, using the thresholds from planning.md's transparency-label table.

    Runs on the combined confidence score produced by combine_signals().
    """
    if score < 0.4:
        return "Human-Authored Content"
    if score < 0.7:
        return "Attribution Uncertain"
    return "AI-Generated Content"


def transparency_label(score: float) -> dict:
    """
    Build the reader-facing transparency label for a confidence score, using the
    three variants designed in planning.md's Transparency Label Design section.

    The variant — and therefore the display text and explanation — changes with
    the score; it is never a fixed string. Returns a structured label so the UI
    can show a headline (display_text) plus a plain-language line that makes the
    confidence level meaningful to a non-technical reader.

        0.0 <= score < 0.4  -> High-Confidence Human -> "Human-Authored Content"
        0.4 <= score < 0.7  -> Uncertain Result      -> "Attribution Uncertain"
        0.7 <= score <= 1.0 -> High-Confidence AI     -> "AI-Generated Content"
    """
    if score < 0.4:
        return {
            "variant": "High-Confidence Human",
            "display_text": "Human-Authored Content",
            "explanation": (
                "Our analysis indicates this content was very likely written by "
                "a person."
            ),
        }
    if score < 0.7:
        return {
            "variant": "Uncertain Result",
            "display_text": "Attribution Uncertain",
            "explanation": (
                "Our analysis could not confidently determine whether this "
                "content was written by a person or generated by AI."
            ),
        }
    return {
        "variant": "High-Confidence AI",
        "display_text": "AI-Generated Content",
        "explanation": (
            "Our analysis indicates this content was very likely generated by "
            "an AI system."
        ),
    }

# ── Rate limiting ────────────────────────────────────────────────────────────
# Keyed by client IP. No global default; the submission endpoint sets its own
# limit via the @limiter.limit decorator below (reasoning documented in README).
# In-memory storage is fine for local dev / a single process.
limiter = Limiter(
    key_func=get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

# ── Audit log ────────────────────────────────────────────────────────────────
# Every attribution decision and appeal is recorded as a structured entry, kept
# both in memory (for fast GET /log) and appended to an on-disk JSON Lines file
# so entries survive restarts and content_ids stay resolvable for appeals (M5).
AUDIT_LOG_PATH = os.path.join(os.path.dirname(__file__), "audit_log.jsonl")
AUDIT_LOG = []


def _load_audit_log() -> None:
    """Load existing audit entries from disk into memory at startup."""
    if not os.path.exists(AUDIT_LOG_PATH):
        return
    with open(AUDIT_LOG_PATH, "r", encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if line:
                AUDIT_LOG.append(json.loads(line))


def _log_decision(entry: dict) -> None:
    """Append one structured entry to the audit log (memory + disk)."""
    AUDIT_LOG.append(entry)
    with open(AUDIT_LOG_PATH, "a", encoding="utf-8") as fh:
        fh.write(json.dumps(entry) + "\n")


def _save_audit_log() -> None:
    """
    Rewrite the whole audit log to disk. Used when an existing entry changes
    (e.g. an appeal flips a submission's status), which a plain append can't do.
    """
    with open(AUDIT_LOG_PATH, "w", encoding="utf-8") as fh:
        for e in AUDIT_LOG:
            fh.write(json.dumps(e) + "\n")


_load_audit_log()


# ── Routes ───────────────────────────────────────────────────────────────────

@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")  # submission cap (reasoning in README)
def submit():
    """
    Accept a piece of text content and return its attribution result.

    Request JSON:
        { "text": "<content to analyze>", "creator_id": "<creator id>" }

    Response JSON (M3 shape — confidence/label filled in M4/M5):
        {
            "content_id":      int,
            "signals":         { "groq": {...}, "stylometric": {...} },
            "confidence_score": float | null,   # M4
            "label":           str | null,      # M5
            "status":          "Public"
        }
    """
    data = request.get_json(silent=True) or {}
    text = data.get("text", "")
    creator_id = data.get("creator_id")

    # Input validation
    if not text or not text.strip():
        return jsonify({"error": "Field 'text' is required and cannot be empty."}), 400

    # ── Detection pipeline ───────────────────────────────────────────────────
    # Signal 1 (M3): Groq — fully implemented.
    groq_result = groq_signal(text)

    # Signal 2 (M4): Stylometric heuristics — currently a neutral stub.
    stylometric_result = stylometric_signal(text)

    llm_score = groq_result["score"]               # Signal 1 (Groq)
    stylometric_score = stylometric_result["score"]  # Signal 2 (stylometric)

    # ── Confidence scoring ───────────────────────────────────────────────────
    # Combine Score 1 and Score 2 per planning.md's Detection Signals section:
    #   weighted_mean - (0.5 * abs(groq_score - stylometric_score))
    combination = combine_signals(groq_result, stylometric_result)
    confidence = combination["combined_score"]

    # Attribution category derived from the combined confidence score.
    attribution = _attribution_from_score(confidence)

    # ── Transparency label ───────────────────────────────────────────────────
    # Reader-facing label; the variant changes with the confidence score.
    label = transparency_label(confidence)

    content_id = str(uuid.uuid4())

    # ── Audit log ────────────────────────────────────────────────────────────
    entry = {
        "type": "submission",
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": _utc_timestamp(),
        "attribution": attribution,
        "confidence": confidence,                 # combined confidence score
        "llm_score": llm_score,                   # Signal 1 (Groq)
        "stylometric_score": stylometric_score,   # Signal 2 (stylometric)
        "label": label,                           # reader-facing transparency label
        "status": "classified",
        "appealed": False,          # flips to True if the creator files an appeal
        "text": text,               # retained for the M5 appeal review view
        "signals": {
            "groq": groq_result,
            "stylometric": stylometric_result,
        },
        "combination": combination,  # how the confidence score was reached
    }
    _log_decision(entry)

    # ── Response ─────────────────────────────────────────────────────────────
    return jsonify({
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": entry["timestamp"],
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": llm_score,
        "stylometric_score": stylometric_score,
        "label": label,
        "status": "classified",
        "signals": {
            "groq": groq_result,
            "stylometric": stylometric_result,
        },
        "combination": combination,
    }), 200


@app.route("/appeal", methods=["POST"])
def appeal():
    """
    Let a creator contest a classification (appeal flow from planning.md):

        POST /appeal -> update content status -> append appeal to audit log
                     -> confirmation

    Request JSON:
        {
            "content_id":        "<id from an earlier /submit response>",
            "creator_reasoning": "<why the creator disputes the result>",
            "evidence":          "<optional supporting evidence>"
        }

    Effects:
        - flips the original content's status to "under_review",
        - appends an appeal entry to the audit log, linked to the original
          classification decision and carrying the creator's reasoning,
        - returns a confirmation. No automated re-classification is performed.
    """
    data = request.get_json(silent=True) or {}
    content_id = data.get("content_id")
    creator_reasoning = data.get("creator_reasoning")
    evidence = data.get("evidence")  # optional supporting evidence

    # Input validation
    if not content_id or not str(content_id).strip():
        return jsonify({"error": "Field 'content_id' is required."}), 400
    if not creator_reasoning or not creator_reasoning.strip():
        return jsonify({"error": "Field 'creator_reasoning' is required and cannot be empty."}), 400

    # Look up the original submission decision for this content.
    original = next(
        (e for e in AUDIT_LOG
         if e.get("type") == "submission" and e.get("content_id") == content_id),
        None,
    )
    if original is None:
        return jsonify({
            "error": f"No submitted content found with content_id '{content_id}'."
        }), 404

    # Status change event: the content moves into the human-review queue.
    original["status"] = "under_review"
    original["appealed"] = True

    # Append the appeal alongside a snapshot of the original classification.
    appeal_entry = {
        "type": "appeal",
        "content_id": content_id,
        "creator_id": original.get("creator_id"),
        "timestamp": _utc_timestamp(),
        "status": "under_review",
        "appeal_reasoning": creator_reasoning,
        "evidence": evidence,
        "original_classification": {
            "classified_at": original.get("timestamp"),
            "confidence": original.get("confidence"),
            "attribution": original.get("attribution"),
            "label": original.get("label"),
            "llm_score": original.get("llm_score"),
            "stylometric_score": original.get("stylometric_score"),
        },
    }
    AUDIT_LOG.append(appeal_entry)
    _save_audit_log()  # persist both the status change and the new appeal entry

    return jsonify({
        "message": "Appeal received. This content is now under review by a human moderator.",
        "content_id": content_id,
        "status": "under_review",
        "appeal_reasoning": creator_reasoning,
    }), 200


@app.route("/log", methods=["GET"])
def get_log():
    """
    Return the audit log as JSON, most recent first.

    Optional query param:
        ?limit=N  -> return only the N most recent entries (handy for README
                     snippets). Omit to return all entries.
    """
    entries = list(reversed(AUDIT_LOG))  # newest first

    limit = request.args.get("limit", type=int)
    if limit is not None and limit >= 0:
        entries = entries[:limit]

    return jsonify({"entries": entries}), 200


@app.route("/health", methods=["GET"])
def health():
    """Lightweight liveness check."""
    return jsonify({"status": "ok"}), 200


if __name__ == "__main__":
    app.run(debug=True, port=int(os.getenv("PORT", "5000")))
