"""
signals.py

The detection signals for Provenance Guard's multi-signal detection pipeline.

Per planning.md, the pipeline uses two distinct signals, each emitting a score
on a 0.0–1.0 scale where:

    0.0  ->  confidently HUMAN-authored
    1.0  ->  confidently AI-generated

Signal 1 — Groq (this milestone, M3):
    Measures the "vibe" and semantic coherence of the text using an LLM judge.
    Returns a JSON object with a calibrated score and a short rationale.

Signal 2 — Stylometric Heuristics (M4):
    Type-Token Ratio, sentence-length variance, punctuation density.
    Stubbed below; to be implemented in M4.

Test the Groq signal directly (see `__main__`) before wiring it into the
/submit endpoint.
"""

import os
import re
import json
import statistics

from dotenv import load_dotenv
from groq import Groq

# Setup: load the Groq key from .env and connect to the LLM (same pattern as
# project1's generate.py).
load_dotenv()
client = Groq(api_key=os.getenv("GROQ_API_KEY"))

MODEL_NAME = "llama-3.3-70b-versatile"

# The Groq signal is asked to act as an attribution judge and return a strict
# JSON object so the score is machine-readable. We tell it the exact scale and
# the meaning of the endpoints so its output is calibrated to the rest of the
# pipeline.
GROQ_SYSTEM_PROMPT = (
    "You are a text-attribution judge. Given a piece of text, estimate the "
    "probability that it was generated by an AI language model rather than "
    "written by a human.\n"
    "Judge based on semantic coherence, the 'vibe' of the prose, predictability "
    "of phrasing, and tell-tale AI patterns (over-smooth transitions, generic "
    "hedging, uniform tone).\n"
    "Respond with a STRICT, valid JSON object and nothing else, with exactly "
    "these two keys:\n"
    '  "score":     a number from 0.0 to 1.0, where 0.0 means confidently '
    "human-written and 1.0 means confidently AI-generated.\n"
    '  "reasoning": a one-sentence explanation of the main factors behind the score.\n'
    "Both the reasoning value MUST be a double-quoted JSON string. Example of a "
    "valid response:\n"
    '{"score": 0.83, "reasoning": "The prose is overly polished and relies on '
    'generic buzzwords."}'
)


def groq_signal(text: str) -> dict:
    """
    Signal 1: ask the Groq LLM to judge how AI-generated the text looks.

    Args:
        text: The raw content submitted for attribution analysis.

    Returns:
        A JSON-style dict:
            {
                "signal":    "groq",
                "score":     float in [0.0, 1.0]  (1.0 = AI, 0.0 = human),
                "reasoning": str,
                "error":     None on success, or an error message string.
            }
        On any failure (empty input, API error, malformed JSON) the score
        falls back to 0.5 (maximally uncertain) and "error" is populated so the
        caller can decide how to treat a degraded signal.
    """
    # Guard: empty / whitespace-only input never reaches the LLM.
    if not text or not text.strip():
        return {
            "signal": "groq",
            "score": 0.5,
            "reasoning": "No text provided.",
            "error": "empty_input",
        }

    try:
        response = client.chat.completions.create(
            model=MODEL_NAME,
            messages=[
                {"role": "system", "content": GROQ_SYSTEM_PROMPT},
                {"role": "user", "content": f"Text to judge:\n\n{text}"},
            ],
            temperature=0.0,  # deterministic-as-possible scoring
            response_format={"type": "json_object"},  # force valid JSON output
        )
        raw = response.choices[0].message.content
        parsed = json.loads(raw)

        # Clamp to [0, 1] in case the model returns something out of range.
        score = float(parsed.get("score", 0.5))
        score = max(0.0, min(1.0, score))

        return {
            "signal": "groq",
            "score": score,
            "reasoning": parsed.get("reasoning", ""),
            "error": None,
        }

    except (json.JSONDecodeError, ValueError, KeyError) as exc:
        # Model returned something we couldn't parse into a score.
        return {
            "signal": "groq",
            "score": 0.5,
            "reasoning": "Could not parse a score from the model response.",
            "error": f"parse_error: {exc}",
        }
    except Exception as exc:  # network / auth / rate-limit errors from Groq
        return {
            "signal": "groq",
            "score": 0.5,
            "reasoning": "The attribution model could not be reached.",
            "error": f"api_error: {exc}",
        }


def stylometric_signal(text: str) -> dict:
    """
    Signal 2: stylometric heuristics.

    Computes three raw metrics and folds them into one 0.0–1.0 AI-likelihood
    score (0.0 = human, 1.0 = AI), matching the groq_signal() dict shape:

    1. Sentence-length burstiness — the coefficient of variation (std / mean)
       of words-per-sentence. Humans write "bursty" prose (a mix of short and
       long sentences -> HIGH variation); LLMs tend toward uniform sentence
       lengths (LOW variation). So low burstiness pushes the score toward AI.
       This is the strongest of the three (weight 0.5).

    2. Type-Token Ratio (TTR) — unique words / total words. Restricted,
       repetitive vocabulary (LOW TTR) leans AI; diverse vocabulary (HIGH TTR)
       leans human. Length-sensitive, so it carries a smaller weight (0.2).

    3. Punctuation density — punctuation marks / words. Dense, "proper"
       comma/clause-heavy punctuation leans AI; sparse punctuation (casual
       human writing) leans human (weight 0.3).

    Each raw metric is linearly mapped onto a [0, 1] sub-score against
    documented human/AI anchor points, then combined as a weighted average.
    """
    if not text or not text.strip():
        return {
            "signal": "stylometric",
            "score": 0.5,
            "reasoning": "No text provided.",
            "metrics": {},
            "error": "empty_input",
        }

    # ── raw metrics ──────────────────────────────────────────────────────────
    words = re.findall(r"[A-Za-z']+", text.lower())
    total_words = len(words)

    if total_words == 0:
        return {
            "signal": "stylometric",
            "score": 0.5,
            "reasoning": "No word tokens found.",
            "metrics": {},
            "error": "no_words",
        }

    # 1. Type-Token Ratio
    ttr = len(set(words)) / total_words

    # 2. Sentence-length burstiness (coefficient of variation)
    sentences = [s for s in re.split(r"[.!?]+", text) if s.strip()]
    sent_word_counts = [len(re.findall(r"[A-Za-z']+", s)) for s in sentences]
    sent_word_counts = [c for c in sent_word_counts if c > 0]

    if len(sent_word_counts) >= 3:
        mean_len = statistics.mean(sent_word_counts)
        sent_cv = statistics.pstdev(sent_word_counts) / mean_len if mean_len else 0.0
    else:
        # Variance over 1–2 sentences is statistically meaningless — treat as
        # neutral rather than letting a coincidence dominate the score.
        sent_cv = None

    # 3. Punctuation density
    punct_count = len(re.findall(r"[,.;:!?\-—()\"']", text))
    punct_density = punct_count / total_words

    # ── map each raw metric onto a 0–1 AI-likelihood sub-score ────────────────
    # Burstiness: CV >= 0.6 -> human (0.0); CV == 0 -> AI (1.0).
    if sent_cv is None:
        burst_sub = 0.5  # neutral when we can't measure it
    else:
        burst_sub = _scale(sent_cv, human_at=0.6, ai_at=0.0)

    # TTR: >= 0.75 -> human (0.0); <= 0.4 -> AI (1.0).
    ttr_sub = _scale(ttr, human_at=0.75, ai_at=0.4)

    # Punctuation density: <= 0.08 -> human (0.0); >= 0.28 -> AI (1.0).
    # (Anchors kept loose so ordinary comma-rich prose doesn't max out.)
    punct_sub = _scale(punct_density, human_at=0.08, ai_at=0.28)

    # ── weighted combination ─────────────────────────────────────────────────
    score = (0.5 * burst_sub) + (0.2 * ttr_sub) + (0.3 * punct_sub)
    score = max(0.0, min(1.0, score))

    reasoning = (
        f"burstiness(cv={_fmt(sent_cv)})->{burst_sub:.2f}, "
        f"ttr={ttr:.2f}->{ttr_sub:.2f}, "
        f"punct_density={punct_density:.2f}->{punct_sub:.2f}"
    )

    return {
        "signal": "stylometric",
        "score": round(score, 4),
        "reasoning": reasoning,
        "metrics": {
            "type_token_ratio": round(ttr, 4),
            "sentence_length_cv": (round(sent_cv, 4) if sent_cv is not None else None),
            "punctuation_density": round(punct_density, 4),
            "num_sentences": len(sent_word_counts),
            "num_words": total_words,
        },
        "error": None,
    }


# ── confidence scoring (signal combination) ─────────────────────────────────

# Weights for the two signals. Groq carries the large majority of the weight
# because it reads semantics directly and detects fluent AI reliably; the
# stylometric signal is noisy and under-detects fluent AI (it scored all four
# calibration inputs low — see README), so it acts only as a minor corroborator
# that nudges, never vetoes, the LLM's judgment.
WEIGHT_GROQ = 0.80
WEIGHT_STYLOMETRIC = 0.20


def combine_signals(groq_result: dict, stylometric_result: dict,
                    w_groq: float = WEIGHT_GROQ,
                    w_stylo: float = WEIGHT_STYLOMETRIC) -> dict:
    """
    Combine the two signal scores into a single confidence score as a weighted
    mean:

        combined = (w_groq * groq_score) + (w_stylo * stylometric_score)

    The result is clamped to [0.0, 1.0], where 0.0 = confidently human and
    1.0 = confidently AI.

    Why a plain weighted mean (and not the earlier disagreement-penalty
    formula): calibration testing showed the subtractive penalty dragged
    confident, correct AI detections down into the "human" band whenever the
    weak stylometric signal disagreed — a confidently-wrong failure. Trusting
    the stronger signal via weighting fixes this. Uncertainty is still
    represented through the 0.4–0.7 "uncertain" label band.

    `disagreement` is reported for transparency/audit but no longer alters the
    score. A signal that errored contributes its neutral 0.5 fallback (set
    upstream), so the combination degrades gracefully rather than crashing.

    Returns a breakdown dict so the audit log can record *how* the score was
    reached, not just the final number.
    """
    g = groq_result.get("score", 0.5)
    s = stylometric_result.get("score", 0.5)

    weighted_mean = (w_groq * g) + (w_stylo * s)
    disagreement = abs(g - s)
    combined = max(0.0, min(1.0, weighted_mean))

    return {
        "combined_score": round(combined, 4),
        "weighted_mean": round(weighted_mean, 4),
        "disagreement": round(disagreement, 4),
        "groq_score": g,
        "stylometric_score": s,
        "weights": {"groq": w_groq, "stylometric": w_stylo},
    }


def _scale(value: float, human_at: float, ai_at: float) -> float:
    """
    Linearly map a raw metric to a [0, 1] AI-likelihood sub-score, clamped.

    Returns 0.0 when value == human_at and 1.0 when value == ai_at, interpolating
    linearly in between. Works in either direction (human_at may be greater or
    less than ai_at).
    """
    if ai_at == human_at:
        return 0.5
    frac = (value - human_at) / (ai_at - human_at)
    return max(0.0, min(1.0, frac))


def _fmt(value) -> str:
    """Format an optional float for the reasoning string."""
    return f"{value:.2f}" if value is not None else "n/a"


# ── direct test harness ─────────────────────────────────────────────────────
# Per the AI Tool Plan, test the first signal with a few inputs directly before
# wiring it into the endpoint:  python signals.py

if __name__ == "__main__":
    samples = {
        "Clearly AI-ish": (
            "In today's fast-paced digital landscape, leveraging cutting-edge "
            "solutions is essential. By embracing innovation and fostering "
            "collaboration, organizations can unlock their full potential and "
            "drive meaningful, sustainable growth across every dimension."
        ),
        "Clearly human-ish": (
            "honestly i didn't even want to go but my roommate dragged me out "
            "and it ended up being kinda fun? the band was loud and we got "
            "tacos after at like 1am. worth it i guess lol."
        ),
        "Empty input": "",
    }

    # Extra samples for the stylometric signal, including planning.md edge cases.
    stylometric_samples = dict(samples)
    stylometric_samples["Repetitive poem (edge case)"] = (
        "I run. I run fast. I run far. I run all day. "
        "I run alone. I run again. I run and run and run."
    )
    stylometric_samples["Technical docs (edge case)"] = (
        "The function accepts a string. The function returns a value. "
        "The function raises an error on invalid input. The function logs "
        "each call. The function is thread-safe."
    )

    print("########## SIGNAL 1: groq_signal ##########")
    for label, text in samples.items():
        result = groq_signal(text)
        print(f"\n=== {label} ===")
        print(f"  score:     {result['score']}")
        print(f"  reasoning: {result['reasoning']}")
        print(f"  error:     {result['error']}")

    print("\n\n########## SIGNAL 2: stylometric_signal ##########")
    for label, text in stylometric_samples.items():
        result = stylometric_signal(text)
        print(f"\n=== {label} ===")
        print(f"  score:     {result['score']}")
        print(f"  metrics:   {result.get('metrics')}")
        print(f"  reasoning: {result['reasoning']}")
        print(f"  error:     {result['error']}")
