"""
signals.py

The detection signals for Provenance Guard's multi-signal detection pipeline.

Per planning.md, the pipeline uses two distinct signals, each emitting a score
on a 0.0–1.0 scale where:

    0.0  ->  confidently HUMAN-authored
    1.0  ->  confidently AI-generated

Signal 1 — Groq (this milestone, M3):
    Measures the "vibe" and semantic coherence of the text using an LLM judge.
    Returns a JSON object with a calibrated score and a short rationale.

Signal 2 — Stylometric Heuristics (M4):
    Type-Token Ratio, sentence-length variance, punctuation density.
    Stubbed below; to be implemented in M4.

Test the Groq signal directly (see `__main__`) before wiring it into the
/submit endpoint.
"""

import os
import json

from dotenv import load_dotenv
from groq import Groq

# Setup: load the Groq key from .env and connect to the LLM (same pattern as
# project1's generate.py).
load_dotenv()
client = Groq(api_key=os.getenv("GROQ_API_KEY"))

MODEL_NAME = "llama-3.3-70b-versatile"

# The Groq signal is asked to act as an attribution judge and return a strict
# JSON object so the score is machine-readable. We tell it the exact scale and
# the meaning of the endpoints so its output is calibrated to the rest of the
# pipeline.
GROQ_SYSTEM_PROMPT = (
    "You are a text-attribution judge. Given a piece of text, estimate the "
    "probability that it was generated by an AI language model rather than "
    "written by a human.\n"
    "Judge based on semantic coherence, the 'vibe' of the prose, predictability "
    "of phrasing, and tell-tale AI patterns (over-smooth transitions, generic "
    "hedging, uniform tone).\n"
    "Respond with a STRICT, valid JSON object and nothing else, with exactly "
    "these two keys:\n"
    '  "score":     a number from 0.0 to 1.0, where 0.0 means confidently '
    "human-written and 1.0 means confidently AI-generated.\n"
    '  "reasoning": a one-sentence explanation of the main factors behind the score.\n'
    "Both the reasoning value MUST be a double-quoted JSON string. Example of a "
    "valid response:\n"
    '{"score": 0.83, "reasoning": "The prose is overly polished and relies on '
    'generic buzzwords."}'
)


def groq_signal(text: str) -> dict:
    """
    Signal 1: ask the Groq LLM to judge how AI-generated the text looks.

    Args:
        text: The raw content submitted for attribution analysis.

    Returns:
        A JSON-style dict:
            {
                "signal":    "groq",
                "score":     float in [0.0, 1.0]  (1.0 = AI, 0.0 = human),
                "reasoning": str,
                "error":     None on success, or an error message string.
            }
        On any failure (empty input, API error, malformed JSON) the score
        falls back to 0.5 (maximally uncertain) and "error" is populated so the
        caller can decide how to treat a degraded signal.
    """
    # Guard: empty / whitespace-only input never reaches the LLM.
    if not text or not text.strip():
        return {
            "signal": "groq",
            "score": 0.5,
            "reasoning": "No text provided.",
            "error": "empty_input",
        }

    try:
        response = client.chat.completions.create(
            model=MODEL_NAME,
            messages=[
                {"role": "system", "content": GROQ_SYSTEM_PROMPT},
                {"role": "user", "content": f"Text to judge:\n\n{text}"},
            ],
            temperature=0.0,  # deterministic-as-possible scoring
            response_format={"type": "json_object"},  # force valid JSON output
        )
        raw = response.choices[0].message.content
        parsed = json.loads(raw)

        # Clamp to [0, 1] in case the model returns something out of range.
        score = float(parsed.get("score", 0.5))
        score = max(0.0, min(1.0, score))

        return {
            "signal": "groq",
            "score": score,
            "reasoning": parsed.get("reasoning", ""),
            "error": None,
        }

    except (json.JSONDecodeError, ValueError, KeyError) as exc:
        # Model returned something we couldn't parse into a score.
        return {
            "signal": "groq",
            "score": 0.5,
            "reasoning": "Could not parse a score from the model response.",
            "error": f"parse_error: {exc}",
        }
    except Exception as exc:  # network / auth / rate-limit errors from Groq
        return {
            "signal": "groq",
            "score": 0.5,
            "reasoning": "The attribution model could not be reached.",
            "error": f"api_error: {exc}",
        }


def stylometric_signal(text: str) -> dict:
    """
    Signal 2 (M4 — STUB): Type-Token Ratio, sentence-length variance, and
    punctuation density combined into a 0.0–1.0 score.

    Returns the same dict shape as groq_signal(). For now it returns a neutral
    placeholder so the pipeline contract is stable.
    """
    # TODO (M4): compute TTR, sentence-length variance, punctuation density,
    # and map them onto a 0.0–1.0 AI-likelihood score.
    return {
        "signal": "stylometric",
        "score": 0.5,
        "reasoning": "Stylometric signal not yet implemented (M4).",
        "error": "not_implemented",
    }


# ── direct test harness ─────────────────────────────────────────────────────
# Per the AI Tool Plan, test the first signal with a few inputs directly before
# wiring it into the endpoint:  python signals.py

if __name__ == "__main__":
    samples = {
        "Clearly AI-ish": (
            "In today's fast-paced digital landscape, leveraging cutting-edge "
            "solutions is essential. By embracing innovation and fostering "
            "collaboration, organizations can unlock their full potential and "
            "drive meaningful, sustainable growth across every dimension."
        ),
        "Clearly human-ish": (
            "honestly i didn't even want to go but my roommate dragged me out "
            "and it ended up being kinda fun? the band was loud and we got "
            "tacos after at like 1am. worth it i guess lol."
        ),
        "Empty input": "",
    }

    for label, text in samples.items():
        result = groq_signal(text)
        print(f"\n=== {label} ===")
        print(f"  score:     {result['score']}")
        print(f"  reasoning: {result['reasoning']}")
        print(f"  error:     {result['error']}")
